spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/festival
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/festival
    username: festivaltest
    password: 1234

  devtools:
    restart:
      enabled: true

  servlet:
    multipart:
      maxFileSize: 20MB       # 파일 한개당 최대 크기
      maxRequestSize: 100MB   # 요청당 최대 파일 크기

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

server:
  error:
    whitelabel:
      enabled=false:
    path=/error: